name: freshflow
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  google_fonts: ^6.0.0
  flutter_map: ^6.0.0
  provider: ^6.0.0
  flutter_svg: ^2.0.0
  latlong2: ^0.9.0
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  slide_to_act: ^2.0.2
  connectivity_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
