name: vego
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.0.0
  google_fonts: ^6.0.0
  flutter_map: ^6.0.0
  provider: ^6.1.5+1
  flutter_riverpod: ^2.4.0
  go_router: ^14.0.0
  flutter_svg: ^2.0.0
  latlong2: ^0.9.0
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  slide_to_act: ^2.0.2
  connectivity_plus: ^6.0.0
  http: ^1.2.0
  dynamic_color: ^1.8.1
  cached_network_image: ^3.3.0
  page_transition: ^2.1.0
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  # assets:
  #   - .env
